---
---
:skip-front-matter:

= Problem Set 6: Sentimental

== tl;dr

[start=0]
. Watch link:/lectures/week-6[Lecture 6]
. Port some programs from C to Python.
. Submit your code.

== Help

For information on (or help with) this Problem Set:

[start=0]
. Watch the walkthroughs herein.
. Attend your tutor's *section*.
* Use `help50` (if unsure what an error message means) and `debug50` (if your code is buggy).
. Ask questions during office hours using the "Ask" tool on this website.
. Visit (or email) the course's heads.

== Academic Honesty

Do keep in mind the course's policy on link:/#academic_honesty[academic honesty], particularly its link:/#regret["regret clause"].

== Getting Started

[source]
----
update50
mkdir ~/workspace/pset6/
cd ~/workspace/pset6/
----

== Problems

. Implement link:sentimental/sentimental[Sentimental].

== How to Submit

=== Step 1 of 2

. Execute `update50`
. Execute `cd ~/workspace/pset6/hello/ && submit50 cs50/2018/spring/sentimental/hello`
. Execute at least one of:
+
--
* `cd ~/workspace/pset6/mario && submit50 cs50/2018/spring/sentimental/mario/less`
* `cd ~/workspace/pset6/mario && submit50 cs50/2018/spring/sentimental/mario/more`
--
. Execute at least one of:
+
--
* `cd ~/workspace/pset6/cash/ && submit50 cs50/2018/spring/sentimental/cash`
* `cd ~/workspace/pset6/credit/ && submit50 cs50/2018/spring/sentimental/credit`
--
. Execute at least one of:
+
--
* `cd ~/workspace/pset6/caesar/ && submit50 cs50/2018/spring/sentimental/caesar`
* `cd ~/workspace/pset6/vigenere/ && submit50 cs50/2018/spring/sentimental/vigenere`
* `cd ~/workspace/pset6/crack/ && submit50 cs50/2018/spring/sentimental/crack`
--


=== Step 2 of 2

Submit https://forms.cs50.net/2018/spring/psets/6[]!

This was Problem Set 6.
