---
---
:skip-front-matter:

= Problem Set 6: Sentimental

== tl;dr

[start=0]
. Watch link:/lectures/lecture-8[Lecture 8]
. Port some programs from C to Python.
. Submit your code.

== Help

For information on (or help with) this Problem Set:

[start=0]
. Watch the walkthroughs herein.
. Attend your tutor's *section*.
. Use `help50` (if unsure what an error message means) and `debug50` (if your code is buggy).
. Ask questions during office hours using the "Ask" tool on this website.
. Visit (or email) the course's heads.

== Academic Honesty

Do keep in mind the course's policy on link:/#academic_honesty[academic honesty], particularly its link:/#regret["regret clause"].

== Getting Started

[source]
----
update50
mkdir ~/workspace/pset6/
cd ~/workspace/pset6/
----

== Problems

All code that you write should be consistent with https://www.python.org/dev/peps/pep-0008/[Style Guide for Python Code], otherwise known as PEP 8.

. Implement link:/problems/sentimental/[Sentimental].

== How to Submit

. Make sure you are signed in to this website!
. Zip your "pset6"-folder using `zip <target> <source>` where both target and source can be "pset6".
. In the form below, add the files that you downloaded.
. Press "Submit for grading". Presto!

This was Problem Set 6.
