---
---

= Resize

== tl;dr

Implement a program that resizes BMPs, per the below.

[source,subs=quotes]
----
$ [underline]#./resize .25 large.bmp small.bmp#
----

[source,subs=quotes]
----
$ [underline]#./resize 4 small.bmp large.bmp#
----

If among those "less comfortable" with programming, you might choose to do link:/problems/resize-less[another version of this problem] instead!

== Introduction

video::DL27z7YRxj4[youtube]

== Getting Started

Here's how to download this problem's "distribution code" (i.e., starter code) into your own CS50 IDE. Log into link:https://cs50.io/[CS50 IDE] and then, in a terminal window, execute each of the below.

1. Execute `update50` to ensure your IDE is up-to-date. That command might take a few minutes to finish.
1. Execute `cd` to ensure that you're in `~/workspace/` (i.e., a directory called `workspace` that's in your home directory, aka `~`).
1. Execute `mkdir module4` to make (i.e., create) a directory called `module4` in your home directory.
1. Execute `cd module4` to change into (i.e., open) that directory.
1. Execute `wget http://cdn.cs50.net/2018/fall/psets/3/resize/more/resize.zip` to download a (compressed) ZIP file with this problem's distribution.
1. Execute `unzip resize.zip` to uncompress that file. 
1. Execute `rm resize.zip` followed by `yes` or `y` to delete that ZIP file.
1. Execute `ls`. You should see a directory called `resize`, which was inside of that ZIP file.
1. Execute `cd resize` to change into that directory.
1. Execute `ls`. You should see a directory called `more`.
1. Execute `cd more` to change into that directory.
1. Execute `ls`. You should see this problem's distribution, including `bmp.h`, `copy.c`, `large.bmp`, `small.bmp`, and `smiley.bmp`.

== Background

Be sure you're familiar with the structure of 24-bit uncompressed BMPs, as introduced in link:../../whodunit/whodunit[Whodunit].

== Specification

Implement a program called `resize` that resizes (i.e., enlarges or shrinks) 24-bit uncompressed BMPs by a factor of `f`.

* Implement your program in a file called `resize.c` inside of `~/workspace/module4/more/`.
* Your program should accept exactly three command-line arguments, whereby
+
--
** the first (`f`) must be a floating-point value in (0.0, 100.0],
** the second must be the name of a BMP to be resized, and
** the third must be the name of the resized version to be written.
--
+ If your program is not executed with such, it should remind the user of correct usage, as with `printf`, and `main` should return `1`.
* Your program, if it uses `malloc`, must not leak any memory.

== Usage

Your program should behave per the examples below. Assumed that the underlined text is what some user has typed.

[source,subs=quotes]
----
$ [underline]#./resize#
Usage: ./resize f infile outfile
$ [underline]#echo $?#
1
----

[source,subs=quotes]
----
$ [underline]#./resize .5 large.bmp smaller.bmp#
$ [underline]#echo $?#
0
----

[source,subs=quotes]
----
$ [underline]#./resize 2 small.bmp larger.bmp#
$ [underline]#echo $?#
0
----

== Walkthrough

video::iv9cw-PTSnA[youtube]

== Hints

With a program like this, we could have created `large.bmp` out of `small.bmp` by resizing the latter by a factor of 4 (i.e., by multiplying both its width and its height by 4), per the below.

[source]
----
./resize 4 small.bmp large.bmp
----

You're welcome to get started by copying (yet again) `copy.c` and naming the copy `resize.c`. But spend some time thinking about what it means to resize a BMP, particularly if `f` is in (0.0, 1.0). (You may assume that `n` times the size of `infile` will not exceed 2^32^ - 1. As for a value of `1.0` for `f`, the result should indeed be an `outfile` with dimensions identical to ``infile``'s.) How you handle  floating-point imprecision and rounding is entirely up to you, as is how you handle inevitable loss of detail. Decide which of the fields in `BITMAPFILEHEADER` and `BITMAPINFOHEADER` you might need to modify. Consider whether or not you'll need to add or subtract padding to scanlines. And do be sure to support a value of `1` for `n`, the result of which should be an `outfile` with dimensions identical to ``infile``'s.

If you happen to use `malloc`, be sure to use `free` so as not to leak memory. Try using `valgrind` to check for any leaks!

== Testing

If you'd like to peek at, e.g., ``large.bmp``'s headers (in a more user-friendly way than `xxd` allows), you may execute the below.

[source]
----
~cs50/pset3/peek large.bmp
----

Better yet, if you'd like to compare your outfile's headers against those from the <<_staffs-solution,staff's solution>>, you might want to execute commands like the below. (Think about what each is doing.)

[source]
----
./resize 4 small.bmp student.bmp
~cs50/hacker3/resize 4 small.bmp staff.bmp
~cs50/hacker3/peek student.bmp staff.bmp
----

=== `check50`

Here's how to check the correctness of your code using `check50`. But be sure to compile and test it yourself as well!

[source]
----
check50 --local resize/more@minprog/checks
----

=== `style50`

Here's how to evaluate the style of your code using `style50`.

[source]
----
style50 resize.c
----

== Staff's Solution

To try out the staff's own implementation of `resize`, execute

```
./resize
```

within link:https://sandbox.cs50.io/cf791495-d296-437d-bc60-cf27e43c7622[this sandbox]
