---
---
:skip-front-matter:

= Problem Set 5: Mispellings

== tl;dr

[start=0]
. Watch link:/lectures/lecture-5[Lecture 5].
. Answer some questions about a spell checker.
. Implement a spell checker.
. Submit your code.

== Help

For information on (or help with) this Problem Set:

[start=0]
. Watch the walkthroughs herein.
. Attend your tutor's *section*.
. Use `help50` (if unsure what an error message means) and `debug50` (if your code is buggy).
. Ask questions during office hours using the "Ask" tool on this website.
. Visit (or email) the course's heads.

== Academic Honesty

Do keep in mind the course's policy on link:/#academic_honesty[academic honesty], particularly its link:/#regret["regret clause"].

== Getting Started

Log into https://cs50.io/[cs50.io] and execute the below in a terminal window.

[source]
----
update50
mkdir ~/workspace/pset5/
cd ~/workspace/pset5/
----

== Academic Honesty

Do keep in mind the course's policy on http://docs.cs50.net/2017/fall/syllabus/cs50.html#academic-honesty[academic honesty], particularly its "regret clause."

== Problems

* Implement link:/problems/speller/[Speller]

=== Big Board

If you'd like to put your code to the test against classmates' code (just for fun), upload your solution to our https://bigboard.quinner.nl/[Big Board] website before or after you submit!

== How to Submit

. Make sure you are signed in to this website!
. In the form below, add the files that you downloaded.
. Press "Submit for grading". Presto!

This was Problem Set 5.
